<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'App\Module'                        => __DIR__ . '/Module.php',
    'App\Controller\AppController' => __DIR__ . '/src/App/Controller/AppController.php',
    'AppTest\Framework\TestCase'        => __DIR__ . '/tests/App/Framework/TestCase.php',
    'AppTest\SampleTest'                => __DIR__ . '/tests/App/SampleTest.php',
);
