<?php
namespace App\view;
$title = 'Application';
use Zend\Session\Container;
$user_session = new Container('user');
?>
<script type="text/javascript">
    var mydata =new Array();
</script>
<div id="pager" data-bind="page: {id: 'nav'}">

    <div  data-bind="page: {id: 'login',role : 'start', beforeShow:function(){$('.logout').hide();} }">
        <label id="validuser"></label>
        <?php
        $form = $this->form;
        $form->setAttribute('id', "loginForm");
        $form->prepare();
        echo $this->form()->openTag($form);
        echo $this->formRow($form->get('login_name'));
        echo $this->formRow($form->get('login_pwd'));
        echo $this->formRow($form->get('login'));
        echo $this->form()->closeTag();
        ?>
    </div>
    <div class="row">
        <div class="col-sm-6">
            <div data-bind="page: {id: 'grid', beforeShow:verifyUser()}">
                <div data-bind="stopBinding: true">
                    <div id="table_grid">
                        <h1 style="text-transform: capitalize" data-bind="text:tablename"></h1>
                        <p>
                            <a href="#nav/add" class="btn btn-primary"><span class="glyphicon glyphicon-plus"></span>Add New User</a> <a onclick="plot();" class="btn btn-warning"><span class="glyphicon glyphicon-graph"></span>Academics</a> <a onclick="user();" class="btn btn-warning"><span class="glyphicon glyphicon-graph"></span>Users</a>
                        </p>
                        <input class=" form-inline form-control input-small"  placeholder="search" id="search"  /> <br>
                        <table id="datatable" class="table table-hover table-bordered text-center" data-bind="attr:{name:tablename}" style="background: white; box-shadow: 2px 2px 16px #002A21">
                            <tr data-bind="foreach:cols">
                                <th style="text-transform: capitalize" data-bind="text:$data,click: $root.sort.bind($data,$data)"></th>
                            </tr>
                            <tbody id="tbody_data" data-bind="foreach: mydata">
                            <tr data-bind="foreach:cols , attr:{id:$data['id']}">
                                <!-- ko if: $index() == 0 -->
                                <td><button class="btn btn-danger"  data-bind="attr:{id:$parent['id']}" onclick="deleteUser(this)"><span class="glyphicon glyphicon-trash"></span></button> <button class="btn btn-primary" data-bind="click:$root.tgl.bind($data,$parent),attr:{id:$parent['id']}"><span class="glyphicon glyphicon-edit"></span></button></td>
                                <!-- /ko -->
                                <!-- ko if: $index() != 0 -->
                                <td data-bind="text:$parent[$data]"></td>
                                <!-- /ko -->
                            </tr>
                            <tr hidden="" data-bind="foreach:cols, attr:{id:$data['id']+'hidden'}">
                                <!-- ko if: $index() == 0 -->
                                <td><button data-bind="attr:{id:$parent[$data]}" class="btn btn-success update">Update</button><input type="hidden" data-bind="value: $parent[$data], attr:{name:$data}" /><input type="hidden" data-bind="value: tablename" name="tableName" /><input type="hidden" value="updateC" name="operation" /></td>
                                <!-- /ko -->
                                <!-- ko if: $index() != 0 -->
                                <td><input type="text" class="form-control" data-bind="value: $parent[$data], attr:{name:$data}"/></td>
                                <!-- /ko -->
                            </tr>
                            </tbody>
                        </table>
                        <nav class="pull-right">
                            <input class="form-control" type="text" placeholder="Page Size 5" maxlength="3" id="txt_pageSize"/>
                            <ul data-bind="foreach: tablecount" class="pagination">
                                <li ><a  onclick="paginate(this)" data-bind="text:$data, attr:{id:$data}"></a></li>
                            </ul>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div data-bind="page: {id: 'add' , beforeShow:verifyUser()}">
        <?php
        $form = $this->form;
        $form->setAttribute('id', "addForm");
        $form->prepare();
        echo $this->form()->openTag($form);
        ?>
        <div class="form-group">
            <label for="username">User Name:</label>
            <?php echo $this->formRow($form->get('username')); ?>
        </div>
        <div class="form-group">
            <label for="username">Password:</label>
            <?php
            echo $this->formRow($form->get('add_pwd'));?>
            <?php
            echo "<label style=\"color:red\" id=\"isAddValid\"></label>"; ?>
        </div>
        <div class="form-group">
            <?php
            echo $this->formRow($form->get('add')) . "&nbsp <a class=\"btn btn-danger\" href=\"#nav/grid\">Cancel</a>";
            echo $this->form()->closeTag();
            ?>
        </div>
    </div>
</div>

<script src="<? echo $this->basePath () . '/js/koPager.js';?>" type="text/javascript"></script>
