
<table >
    <tr>
        <th>Name</th>
        <th>Password</th>
        <th>Operation</th>
    </tr>
    <tbody data-bind="foreach: rows">
    <tr>
        <td data-bind="text: name"></td>
        <td data-bind="text: pwd"></td>
        <td data-bind="text: id"></td>
    </tr>
</table>
<script type="text/javascript">
    var dataModel = function() {
        this.rows = ko.observableArray([]);

    };

    $(document).ready(function() {
        var model = new dataModel();
        ko.applyBindings(model);

        $.ajax({
            method : "POST",
            url : "http://192.168.83.130/demoz2/public/app/data",
            success : function(data) {
                data=JSON.parse(data);
                for (var x in data) {
              //      alert(data[x]);
                    model.rows.push(data[x]);

                }
            }
        });
    });

    //    var viewModel = {
    //    };
    //
    //    pager.extendWithPage(viewModel);
    //    ko.applyBindings(viewModel,document.getElementById("abdullah"));
    //
    //    pager.start();
</script>

