<?php echo $this->doctype(); ?>
<?php
use Zend\View\Helper\ServerUrl ;
?>
<html lang="en">
<head>
    <meta charset="utf-8">
    <script type="text/javascript" > var myUrl="<?php echo $this->serverUrl()?>"</script>
    <?php echo $this->headTitle('Application '. $this->translate('Demo'))->setSeparator(' - ')->setAutoEscape(false)?>

    <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0')?>

    <!-- Le styles -->
    <?php

    echo $this->headLink ( array (
        'rel' => 'shortcut icon',
        'type' => 'image/vnd.microsoft.icon',
        'href' => $this->basePath () . '/img/favicon.ico'
    ) )->prependStylesheet ( $this->basePath () . '/css/bootstrap-responsive.min.css' )->prependStylesheet ( $this->basePath () . '/css/style.css' )->prependStylesheet ( '//maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css' )?>

    <!-- Scripts -->
    <?php

    echo $this->headScript ()->prependFile ( $this->basePath () . '/js/html5.js', 'text/javascript', array (
        'conditional' => 'lt IE 9'
    ) )->prependFile ( $this->basePath () . '/js/bootstrap.min.js' )
        ->prependFile ( $this->basePath () . '/js/functions.js' )
        ->prependFile ( $this->basePath () . '/js/ko.pager.js' )
        ->prependFile ( 'https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.js' )
        ->prependFile ( $this->basePath () . '/js/knockout-3.0.0.js' )
        ->prependFile ( $this->basePath () . '/js/socket.io.js' )?>



</head>
<body style="background: url('<?php echo $this->serverUrl()?>/strom/public/img/body.png')" >
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container">
            <a class="btn btn-navbar" data-toggle="collapse"
               data-target=".nav-collapse"> <span class="icon-bar"></span> <span
                    class="icon-bar"></span> <span class="icon-bar"></span>
            </a> <a class="brand" style="background: none"
                    href="<?php echo $this->url('home') ?>"><b style="font-size: 34px;">Strom</b></a>
            <div class="nav-collapse collapse">
                <!-- 		<ul class="nav">
						<li class="active"><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Home') ?></a></li>
					</ul> -->
            </div>
            <!--/.nav-collapse -->
            <div class="pull-right btn btn-warning logout" style="margin-top: 8px;" onclick="logoutUser();">Logout</div>
        </div>
    </div>
</div>
<div class="container">
    <?php echo $this->content; ?>
    <hr>
    <footer>
        <p>Demo Application made By Abdullah</p>
    </footer>
</div>
<!-- /container -->
<?php echo $this->inlineScript()?>
</body>
</html>
